### ISSUE TITLE
Using the Post api mangles multipart/form-data request

### ISSUE THREAD

**Issue by meelash** [NodeBB/nodebb-plugin-import-users-csv#6]
The post api in public/src/modules/api.js that is being used in this plugin to upload the file takes the payload and tries to stringify it. It also forces the contentType to application and tries to process the data. The first of the errors I encountered is mentioned here: https://community.nodebb.org/post/94592

I've confirmed that these are the issue by temporarily making the following change:
![image](https://github.com/NodeBB/nodebb-plugin-import-users-csv/assets/59001/fd9d9660-fa8c-4305-90ad-035ba5076682)
and confirming that the plugin then works as intended.

Obviously, this is not a solution however, as it would break other uses of that api.

Should I just modify the plugin to not use the api and instead just submit the form using browser submit, the way, for example, the category picture upload works? Or is there another preferred way to fix this?

**Comment by meelash** [comment]
Reference for the processData and contentType needing to be set like this for $.ajax: https://stackoverflow.com/questions/21044798/how-to-use-formdata-for-ajax-file-upload

**Comment by julianlam** [comment]
Ah, hang on. This is fixed in latest develop. Test using that, and if so we'll update the compatibility string.

**Comment by julianlam** [comment]
I basically refactored the API module just for this plugin.

**Comment by julianlam** [comment]
@meelash This is the PR I was referring to.

https://github.com/NodeBB/NodeBB/pull/11768

So it will land in a NodeBB release earliest v3.3.x

**Comment by meelash** [comment]
Yep, thanks @julianlam. I tested on develop and can confirm it fixes the issue.
